version: '3'

services:
  postgres:
    image: "postgres:12.2"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: spaceHomepageReact
      POSTGRES_DB: spaceHomepageReact
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d spaceHomepageReact -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
